// src/lib/i18n.js
// -----------------------------------------------------------------------------
// Tiny in-app translation dictionary for the UI CHROME (buttons, labels, nav).
// Lesson *content* is generated by the LLM in the chosen language; this file only
// covers the fixed interface strings.
//
// We keep it dependency-free: a plain object of { key: { en, fa } } and a t()
// helper. Components receive the current `lang` from App and call t(key, lang).
// -----------------------------------------------------------------------------

export const STRINGS = {
  curriculum: { en: 'Curriculum', fa: 'سرفصل‌ها' },
  cards: { en: 'Cards', fa: 'کارت‌ها' },
  quiz: { en: 'Quiz', fa: 'آزمون' },
  settings: { en: 'Settings', fa: 'تنظیمات' },
  back: { en: '← Curriculum', fa: '← سرفصل‌ها' },
  findMyLevel: { en: 'Find my level', fa: 'تعیین سطح من' },
  retakePlacement: { en: 'Retake placement test', fa: 'آزمون تعیین سطح دوباره' },

  overall: { en: 'Overall', fa: 'پیشرفت کلی' },
  module: { en: 'Module', fa: 'ماژول' },
  notStarted: { en: 'Not started', fa: 'شروع‌نشده' },
  inProgress: { en: 'In progress', fa: 'در حال انجام' },
  completed: { en: 'Completed', fa: 'تکمیل‌شده' },

  generateLesson: { en: 'Generate lesson', fa: 'ساخت درس' },
  regenerate: { en: 'Regenerate', fa: 'ساخت دوباره' },
  markComplete: { en: 'Mark complete', fa: 'علامت‌گذاری تکمیل' },
  imStuck: { en: "I'm stuck", fa: 'گیر کرده‌ام' },
  askFollowUp: { en: 'Ask a follow-up', fa: 'پرسش بیشتر' },
  send: { en: 'Send', fa: 'ارسال' },
  teachBack: { en: 'Teach-back — explain this topic in your own words', fa: 'بازگویی — این مبحث را به زبان خودت توضیح بده' },
  checkUnderstanding: { en: 'Check my understanding', fa: 'سنجش درک من' },
  nextLesson: { en: 'Next lesson →', fa: 'درس بعد →' },
  stop: { en: 'Stop', fa: 'توقف' },
  generating: { en: 'Generating…', fa: 'در حال ساخت…' },

  listen: { en: 'Listen', fa: 'پخش صوتی' },
  stopAudio: { en: 'Stop audio', fa: 'توقف صدا' },
  askByVoice: { en: 'Ask by voice', fa: 'پرسش صوتی' },
  listening: { en: 'Listening…', fa: 'در حال شنیدن…' },

  comprehensionTitle: { en: 'Quick check — what did you grasp?', fa: 'سنجش سریع — چه‌قدر یاد گرفتی؟' },
  startCheck: { en: 'Start understanding check', fa: 'شروع سنجش درک' },
  yourScore: { en: 'Your score', fa: 'امتیاز تو' },

  costLabel: { en: 'cost', fa: 'هزینه' },
  tokens: { en: 'tokens', fa: 'توکن' },
  costUnknown: { en: 'cost n/a', fa: 'هزینه نامشخص' },

  language: { en: 'Language', fa: 'زبان' },
  voice: { en: 'Voice tutor', fa: 'مربی صوتی' },
}

// Return the translated string for a key, falling back to English then the key.
export function t(key, lang = 'en') {
  const entry = STRINGS[key]
  if (!entry) return key
  return entry[lang] || entry.en || key
}

// Farsi is written right-to-left.
export function isRTL(lang) {
  return lang === 'fa'
}
