// vite.config.js
// -----------------------------------------------------------------------------
// Vite build configuration. Vite is our bundler/dev-server: it serves the app
// fast during development and produces an optimized static build for GitHub Pages.
//
// We add two plugins:
//   - @vitejs/plugin-react  -> lets Vite understand React/JSX.
//   - vite-plugin-pwa       -> auto-generates the service worker + web manifest
//                              so the app is installable and works offline.
// -----------------------------------------------------------------------------
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// IMPORTANT — GitHub Pages base path.
// A GitHub Pages "project site" is served from a SUBPATH like:
//   https://<username>.github.io/<repo-name>/
// So every asset URL must be prefixed with "/<repo-name>/".
// Change this string to match YOUR repository name before deploying.
// For local dev this also works (Vite serves the app under this path).
// If you deploy to a custom domain or a "user site" (username.github.io),
// set this to '/'.
const BASE_PATH = process.env.GHPAGES_BASE || '/AI_Learner/'

export default defineConfig({
  base: BASE_PATH,
  plugins: [
    react(),
    VitePWA({
      // 'autoUpdate' = when you ship a new version, the service worker updates
      // itself in the background on the next visit (no manual unregister needed).
      registerType: 'autoUpdate',
      // Files that should be available offline even though they are not part of
      // the JS bundle (our curriculum data + the icon).
      includeAssets: ['icon.svg', 'curriculum.json'],
      manifest: {
        name: 'AI Learning Companion',
        short_name: 'AI Learn',
        description: 'Learn AI from a fixed curriculum. Lessons are generated by an LLM and cached on your device.',
        theme_color: '#f4ede3',
        background_color: '#faf6ef',
        display: 'standalone',
        // start_url / scope are relative so they respect the BASE_PATH above.
        start_url: '.',
        scope: '.',
        icons: [
          // A single scalable SVG covers all sizes. "purpose: any maskable"
          // lets the OS crop it into a circle/rounded-square on the home screen.
          {
            src: 'icon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any maskable',
          },
        ],
      },
      workbox: {
        // Pre-cache the built app shell (html/js/css) so it loads offline.
        globPatterns: ['**/*.{js,css,html,svg,json,woff2}'],
        // Never try to cache calls to the LLM provider — those must hit network
        // (and we don't want to accidentally cache an API response with a key).
        navigateFallbackDenylist: [/^\/api/],
        runtimeCaching: [
          {
            // curriculum.json is fetched at runtime; serve from cache first so
            // the app opens instantly and works offline.
            urlPattern: ({ url }) => url.pathname.endsWith('curriculum.json'),
            handler: 'StaleWhileRevalidate',
            options: { cacheName: 'curriculum-cache' },
          },
        ],
      },
      devOptions: {
        // Enable the service worker during `npm run dev` so you can test PWA
        // behavior without a production build.
        enabled: true,
      },
    }),
  ],
})

// Edge cases this config does NOT handle:
// - It does not auto-detect your repo name; you must edit BASE_PATH yourself.
// - If you rename the repo later, rebuild & redeploy or asset URLs will 404.
